attributes(global) subroutine copy_ILP_shared(odata, idata)
  implicit none
  real(fpKind) :: odata(*), idata(*)
  real(fpKind), shared :: tmp(blockDim%x, ILP)
  integer :: i,j

  i = (blockIdx%x-1)*blockDim%x*ILP + threadIdx%x

  do j = 1, ILP
      tmp(threadIdx%x,j) = idata(i+(j-1)*blockDim%x)
  enddo

  do j = 1, ILP
      odata(i+(j-1)*blockDim%x) = tmp(threadIdx%x,j)
  enddo
end subroutine copy_ILP_shared